/*秀丸エディタから乱数列を生成するマクロ

（概要）
マクロをカスタマイズされる方向けのサンプルです。

（設定）
個数       	 ：入力ボックからユーザーが入力する。
乱数の種類  	：sfmt(SIMD-oriented Fast Mersenne Twister.)
最大最小値の基数：16進法
最小値			：0
最大値			：0xffffffffffffffff
プレフィックス	："0x"
出力の基数		：16進法
区切り			：",\n"
*/
$num = input("生成する乱数の個数を指定して下さい","10");
if(0==strlen($num)){
	endmacro;
}
#num = val($num);
if(#num<=0){
	endmacro;
}

$exe_path = currentmacrodirectory+"\\hm_random_main.mac";
execmacro $exe_path,  $num, "sfmt", "16", "0", "0xffffffffffffffff", "0x", "16", ",\\n";
